### ISSUE TITLE
Sutff to consider while refactoring

### ISSUE THREAD

**Issue by ApplePie420** [Czechball/pidrive-install#3]
Obviously, since new release of hcxdumptool mentioned in #2 , this being basically dead for a while and a shitfuckton of TODOs in comments, this needs to be refactored very intensively. Here is the collection of stuff that needs to get fixed, and some ideas/propositions:

# TODO - Fixes
- [ ] install.sh - Fix for mt7610u drivers - This has been apparently fixed in release 20200619-1, see [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931561#20), **YET TO VERIFY**
- [ ] install.sh - Build and install kernel headers from Linux source - If we are using default config, which apparently we are, then we could simply `sudo apt-get install raspberrypi-kernel-headers`
- [ ] finalize.sh - Disabled realtek_rtwifi build, broken - WIth new upstream driver, this seems to be fixed in kimocoder/realtek_rtwifi#34 , again, **YET TO TEST**

# Ideas
- [ ] Since hcxdumptool deprecated whiltelists completely, we can maybe temporarily disable the functionality completely (but not remove it), so it doesn't create unused dirs/files
- [ ] hcxdumptool in this new version runs in screen refresh mode, rather than waterfall. However this is not necessary for headless operation. As mentioned in https://github.com/ZerBea/hcxdumptool/issues/301#issuecomment-1508011763 , you can compile the software with this make option commented out. Since compilation is already done on-device, this should be very easy to do. 
- [ ] There is now integration of RPi GPIO functionality, see this help snippet:
```
--gpio_button=<digit>          : Raspberry Pi GPIO pin number of button (2...27)
                                  push GPIO button (> 10 seconds) to terminate program
                                  default: 0 (GPIO not in use)
--gpio_statusled=<digit>       : Raspberry Pi GPIO number of status LED (2...27)
                                  default: 0 (GPIO not in use)
```
- [ ] Also, there is now support to shut down or reboot the system based on different (non)failure conditions, this might be usedul while preventing random USB behaviour observed many times, especially when using wonky USB cards, extensions etc.:
```
--exitoneapol=<type>           : exit on first EAPOL occurrence:
                                  bitmask:
                                   1 = PMKID
                                   2 = EAPOL M2
                                   4 = EAPOL M3
                                  target BPF filter is recommended
--onsigterm=<action>           : action when the program has been terminated (poweroff, reboot)
                                  poweroff: power off system
                                  reboot:   reboot system
--ongpiobutton=<action>        : action when the program has been terminated (poweroff, reboot)
                                  poweroff: power off system
                                  reboot:   reboot system
--ontot=<action>               : action when the program has been terminated (poweroff, reboot)
                                  poweroff: power off system
                                  reboot:   reboot system
--onwatchdog=<action>          : action when the program has been terminated (poweroff, reboot)
                                  poweroff: power off system
                                  reboot:   reboot system
--onerror=<action>             : action when the program has been terminated (poweroff, reboot)
                                  poweroff: power off system
                                  reboot:   reboot system
```
- [ ] A cool functionality would be to be able to assign different interfaces to different bands, i.e. have 5GHz capable interface only snoop 5GHz bands, leave 2.4GHz to only /b/n/c capable devices. Also, if there are multiple devices with same frequency capability, a (imho) very dramatic speed improvement would be to split channels evenly between those interfaces (i.e. if 2 2.4GHz itnerfaces are available, assign channels 1-6 to interface0, and channels 7-12 to interface1). Getting to know that interface is made super easy by using `-I <interface>` flag, that returns a very nice details about interface capabilities:
![image](https://github.com/Czechball/pidrive-install/assets/21370314/c27098c6-4ff4-4d4c-a2ab-9764fca2c0fe)
The rules for this might get extremely messy, but with some clever regexes, this shouldn't be much pain to implement

**Comment by ApplePie420** [comment]
Update:
- ability to compile hcxdumptool (and other necessary software) added in faeb318091feda14f4046160912695ed805ef76f and 91e49f467bb993d346e2b10b51ff47c616b157b5
- you can now run the script as any other user than "pi" with a nice selection menu 5c65eca83fc837fff4267e0605ea356b2d27a25e
- fixed non-working interface selector from add-interface.sh 38683a19befbede5be6429d05343308d93ab646e
